CREATE TABLE `dm.store_daily_business_analysis`(
  `id` string COMMENT '主键（门店编码+支付日期+业务类型编码,然后再反转,如：reverse(107U20210415103）',
  `store_code` string COMMENT '门店编码',
  `store_name` string COMMENT '门店名称',
  `store_type` string COMMENT '门店类型',
  `store_status` string COMMENT '门店当日状态（正常营业/关店）',
  `close_date` string COMMENT '关店日期',
  `demolition_date` string COMMENT '拆店日期',
  `l2_company_code` string COMMENT '所属二级子公司编码',
  `l2_company_name` string COMMENT '所属二级子公司名称',
  `franchisee_code` string COMMENT '所属加盟商编码',
  `franchisee_name` string COMMENT '所属加盟商名称',
  `big_area_manager_code` string COMMENT '大区负责人工号',
  `big_area_manager_name` string COMMENT '大区负责人姓名',
  `area_manager_code` string COMMENT '区域负责人工号',
  `area_manager_name` string COMMENT '区域负责人姓名',
  `pay_date` string COMMENT '支付日期,格式：yyyymmdd',
  `business_code` string COMMENT '业务类型编码',
  `business_name` string COMMENT '业务类型名称(103 饿了么,121 百度外卖,100 传统零售,101 美团外卖,102 APP外卖,122 京东到家,155 门店团购,9100 社团核销,9200 直播)',
  `sales_amt_no_discount` decimal(18,2) COMMENT '应收金额',
  `sales_amt` decimal(18,2) COMMENT '实收金额',
  `sales_amt_subsi` decimal(18,2) COMMENT '销售额（含补贴）',
  `sales_amt_pay` decimal(18,2) COMMENT '支付金额',
  `sales_amt_discount` decimal(18,2) COMMENT '优惠金额',
  `sales_amt_refund` decimal(18,2) COMMENT '退款金额',
  `sales_cnt_refund` int COMMENT '退款订单笔数',
  `sales_cnt` int COMMENT '订单笔数（正向）',
  `passenger_flow` int COMMENT '客流（取正向订单数量+逆向订单数量，即：正逆向订单数量绝对值相加，均从POS上取数）')
COMMENT '单店单天数据分析模型-业务类型，基本涵盖观远报表，临时取数，接口调用'
PARTITIONED BY ( `dt` string COMMENT '按支付日期，每天一个分区，格式：yyyy-MM-dd')